export const allCourses = [
  {
    id: 1,
    title: "Business Analysis & Process Management",
    provider: "Coursera Project Network",
    category: "study",
    detail:
      "Skills you'll gain: Business Analysis, Business Process Management",
    rating: "4.4",
  },
  {
    id: 2,
    title: "Build a free website with WordPress",
    provider: "Coursera Project Network",
    category: "study",
    detail: "Skills you'll gain: Creativity, Web Design, Web Development",
    rating: "4.4",
  },
  {
    id: 3,
    title: "Introduction to Microsoft Excel",
    provider: "Coursera Project Network",
    category: "study",
    detail:
      "Skills you'll gain: Data Analysis, Microsoft Excel, Data Management, Leadership and Management",
    rating: "4.6",
  },
  {
    id: 4,
    title: "English for Common Interactions in the Workplace: Basic Level",
    provider: "Pontificia Universidad Cat\u00c3\u00b3lica de Chile",
    category: "study",
    detail: "N/A",
    rating: "4.7",
  },
  {
    id: 5,
    title: "First Step Korean",
    provider: "Yonsei University",
    category: "study",
    detail: "Skills you'll gain: Culture, Writing",
    rating: "4.9",
  },
  {
    id: 6,
    title: "Investment Risk Management",
    provider: "Coursera Project Network",
    category: "study",
    detail: "Skills you'll gain: Leadership and Management, Risk Management",
    rating: "4.3",
  },
  {
    id: 7,
    title: "Creative Thinking: Techniques and Tools for Success",
    provider: "Imperial College London",
    category: "study",
    detail: "Skills you'll gain: Creativity, Problem Solving, Collaboration",
    rating: "4.7",
  },
  {
    id: 8,
    title: "English for Career Development",
    provider: "University of Pennsylvania",
    category: "study",
    detail:
      "Skills you'll gain: Business Communication, Human Resources, Human Resources Operations, Application Development, People Analysis",
    rating: "4.8",
  },
  {
    id: 9,
    title: "Python for Data Science, AI & Development",
    provider: "IBM",
    category: "study",
    detail:
      "Skills you'll gain: Computer Programming, Data Analysis, Python Programming",
    rating: "4.6",
  },
  {
    id: 10,
    title: "Cybersecurity for Everyone",
    provider: "University of Maryland, College Park",
    category: "study",
    detail:
      "Skills you'll gain: Cyberattacks, Human Computer Interaction, Network Security, Security Engineering, Security Strategy, Computer Security Models, Leadership and Management, Risk Management, Software Security, Correlation And Dependence",
    rating: "4.7",
  },
  {
    id: 11,
    title: "Food & Beverage Management",
    provider: "Universit\u00c3\u00a0 Bocconi",
    category: "study",
    detail:
      "Skills you'll gain: Design and Product, Marketing, Business Analysis, Customer Analysis, Product Marketing, Product Strategy, Communication, Entrepreneurship, Leadership and Management, Marketing Management, Strategy",
    rating: "4.8",
  },
  {
    id: 12,
    title: "Financial Markets",
    provider: "Yale University",
    category: "study",
    detail:
      "Skills you'll gain: Finance, Risk Management, Banking, Behavioral Economics, Critical Thinking, Decision Making, Financial Analysis, Innovation, Regulations and Compliance",
    rating: "4.8",
  },
  {
    id: 13,
    title: "Humanities",
    provider: "PredictionX: Lost Without Longitude",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 14,
    title: "Humanities",
    provider: "PredictionX: Omens, Oracles & Prophecies",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 15,
    title: "Social Sciences",
    provider: "Systematic Approaches to Policy Design",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 16,
    title: "Social Sciences",
    provider: "New Ideas for Nonprofit Leaders Webinar",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 17,
    title: "Social Sciences",
    provider: "4P Model for Strategic Leadership Podcasts",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 18,
    title: "Social Sciences",
    provider: "The Science of Corresponding with Busy People Webinar",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 19,
    title: "Computer Science",
    provider: "CS50's Introduction to Programming with Scratch",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 20,
    title: "Social Sciences",
    provider: "Global News & Technology Leadership in Challenging Times",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 21,
    title: "Social Sciences",
    provider:
      "Our Information Emergency: Navigating the Media Environment in 2021",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 22,
    title: "Computer Science",
    provider: "CS50's Introduction to Artificial Intelligence with Python",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 23,
    title: "Computer Science",
    provider: "CS50 for Lawyers",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 24,
    title: "Business",
    provider: "Negotiating Salary",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 25,
    title: "Business",
    provider: "Resilient Leadership",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 26,
    title: "Health & Medicine",
    provider: "Clinical Care for Autistic Adults",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
  {
    id: 27,
    title: "Social Sciences",
    provider:
      "A Darkening Horizon: Nuclear Dangers Around the World with Matthew Bunn",
    category: "study",
    detail: "N/A",
    rating: "N/A",
  },
];
